name: NewsAnalystAgent
model_name: deepseek-r1:70b
max_retries: 3
prompt_template: |
  You are a News Analyst specialized in US tech equity.
  Here is the news article or headline:

  {news_text}

  Determine its impact on the company's stock price:
  - If negative/regulatory or legal issues, bias negative
  - If product breakthroughs, partnerships, or strong financial updates, bias positive

  Output JSON only, example:
  {
    "score": -0.2,
    "comment": "Short reason"
  }
