name: SentimentAnalystAgent
model_name: deepseek-r1:70b
max_retries: 3
prompt_template: |
  You are a Market Sentiment Analyst for US technology stocks.
  The following data represents social media, forums, or other sentiment sources:

  {sentiment_data}

  Provide an overall sentiment rating from -1.0 (very negative) to +1.0 (very positive).
  Also provide a short comment (<= 50 chars).

  Strictly in JSON:
  {
    "score": 0.3,
    "comment": "Short comment"
  }
